apiVersion: batch/v1
kind: CronJob
metadata:
  name: restgoonch-client-cronjob
  labels:
    app: restgoonch-client
spec:
  schedule: "0/8 * * * *"
  jobTemplate:
    metadata:
      labels:
        app: restgoonch-client
    spec:
      template:
        spec:
          containers:
          - name: restgoonch-client
            image: thaigoonch/restgoonch-client:1.6
            imagePullPolicy: IfNotPresent
          restartPolicy: Never
          nodeSelector:
            goonchrole: "nonserver"